# Generated by Django 4.2.1 on 2023-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to=''),
        ),
    ]
