# Generated by Django 4.2.1 on 2023-06-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_id_thread_thread_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thread_id',
            new_name='id',
        ),
    ]
